# Generated by Django 5.0.6 on 2026-07-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='Exact URL called, with the API key redacted.')),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('response_hash', models.CharField(help_text='sha256 of the raw response body.', max_length=64)),
                ('raw_body', models.JSONField(blank=True, null=True)),
                ('is_error', models.BooleanField(default=False)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SimdasiTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=32, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoverageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('dynamic', 'Dynamic Data'), ('static_table', 'Static Table'), ('sdgs', 'SDGs'), ('sdds', 'SDDS'), ('foreign_trade', 'Foreign Trade')], max_length=16)),
                ('admin_level', models.CharField(choices=[('national', 'National'), ('province', 'Province'), ('regency', 'Regency/Kabupaten-Kota')], max_length=16)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unchecked', 'Unchecked'), ('error', 'Error')], default='unchecked', max_length=16)),
                ('years_confirmed', models.JSONField(blank=True, default=list)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.coveragechecklog')),
            ],
        ),
        migrations.CreateModel(
            name='CoverageStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unchecked', 'Unchecked'), ('error', 'Error')], max_length=16)),
                ('new_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unchecked', 'Unchecked'), ('error', 'Error')], max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('check_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.coveragechecklog')),
                ('coverage_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='catalog.coveragerecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=16, unique=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('domain_url', models.CharField(blank=True, max_length=255)),
                ('admin_level', models.CharField(choices=[('national', 'National'), ('province', 'Province'), ('regency', 'Regency/Kabupaten-Kota')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_province', models.ForeignKey(blank=True, limit_choices_to={'admin_level': 'province'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regencies', to='catalog.domain')),
            ],
            options={
                'ordering': ['domain_id'],
            },
        ),
        migrations.AddField(
            model_name='coveragerecord',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='catalog.domain'),
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_category_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_categories', to='catalog.domain')),
            ],
            options={
                'verbose_name_plural': 'subject categories',
                'unique_together': {('subject_category_id', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='catalog.domain')),
                ('subject_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='catalog.subjectcategory')),
            ],
            options={
                'unique_together': {('subject_id', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_id', models.CharField(max_length=16)),
                ('data_model', models.CharField(choices=[('dynamic', 'Dynamic Data'), ('static_table', 'Static Table'), ('sdgs', 'SDGs'), ('sdds', 'SDDS'), ('foreign_trade', 'Foreign Trade')], default='dynamic', max_length=16)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='catalog.domain')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='catalog.subject')),
            ],
            options={
                'unique_together': {('variable_id', 'domain', 'data_model')},
            },
        ),
        migrations.AddField(
            model_name='coveragerecord',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='catalog.variable'),
        ),
        migrations.CreateModel(
            name='VerticalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vervar_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.domain')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_variables', to='catalog.variable')),
            ],
        ),
        migrations.CreateModel(
            name='SimdasiCoverageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfd_region_code', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed'), ('unchecked', 'Unchecked'), ('error', 'Error')], default='unchecked', max_length=16)),
                ('years_confirmed', models.JSONField(blank=True, default=list, help_text='ketersediaan_tahun values confirmed present.')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.coveragechecklog')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='catalog.simdasitable')),
            ],
            options={
                'unique_together': {('table', 'mfd_region_code')},
            },
        ),
        migrations.CreateModel(
            name='PeriodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_id', models.CharField(max_length=16)),
                ('label', models.CharField(max_length=64)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='catalog.variable')),
            ],
            options={
                'unique_together': {('period_id', 'variable')},
            },
        ),
        migrations.AddIndex(
            model_name='coveragerecord',
            index=models.Index(fields=['admin_level', 'status'], name='catalog_cov_admin_l_b149be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coveragerecord',
            unique_together={('variable', 'domain', 'model_type')},
        ),
        migrations.AlterUniqueTogether(
            name='verticalvariable',
            unique_together={('vervar_id', 'variable')},
        ),
    ]
