# Generated by Django 5.0.6 on 2026-07-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simdasitable',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['id']},
        ),
    ]
