# Generated by Django 5.0.6 on 2026-07-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_simdasitable_options_alter_variable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='metadata_crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
