# Generated by Django 5.0.6 on 2026-07-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_subject_metadata_crawled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='stat_admin_levels',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='variable',
            name='stat_data_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variable',
            name='stat_year_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='stat_year_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
