# Generated by Django 5.0.6 on 2026-10-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_trigram_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='catalog.domain'),
        ),
        migrations.AddField(
            model_name='domain',
            name='source',
            field=models.CharField(choices=[('domain_api', 'BPS domain endpoint'), ('data_vervar', 'BPS data response vervar')], default='domain_api', max_length=16),
        ),
        migrations.AddField(
            model_name='domain',
            name='source_check_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.coveragechecklog'),
        ),
    ]
