# Generated by Django 5.0.6 on 2026-07-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApbdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun_key', models.CharField(max_length=128, unique=True)),
                ('label_id', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('pendapatan', 'Pendapatan'), ('belanja', 'Belanja'), ('pembiayaan', 'Pembiayaan')], max_length=16)),
                ('parent_key', models.CharField(blank=True, max_length=128)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'akun_key'],
            },
        ),
        migrations.CreateModel(
            name='DjpkFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('apbd', 'APBD export'), ('provinsi', 'province list'), ('pemda', 'pemda list')], default='apbd', max_length=16)),
                ('url', models.TextField()),
                ('http_status', models.IntegerField()),
                ('byte_count', models.IntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('response_sha256', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ApbdRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djpk_prov', models.CharField(max_length=2)),
                ('djpk_pemda', models.CharField(max_length=2)),
                ('djpk_code', models.CharField(max_length=4, unique=True)),
                ('level', models.CharField(choices=[('province', 'Provinsi'), ('regency', 'Kabupaten/Kota')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('prov_name', models.CharField(blank=True, max_length=255)),
                ('kemendagri_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('match_method', models.CharField(blank=True, max_length=32)),
                ('matched_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['djpk_prov', 'djpk_pemda'],
                'indexes': [models.Index(fields=['level'], name='djpk_apbdre_level_8bcc05_idx'), models.Index(fields=['djpk_prov'], name='djpk_apbdre_djpk_pr_a8ad9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApbdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('report_type', models.CharField(choices=[('apbd', 'APBD (anggaran)'), ('realisasi', 'Realisasi APBD')], max_length=16)),
                ('periode', models.IntegerField(default=12)),
                ('line_count', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='djpk.apbdregion')),
                ('fetch_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='djpk.djpkfetchlog')),
            ],
            options={
                'ordering': ['-tahun', 'region'],
            },
        ),
        migrations.CreateModel(
            name='ApbdLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_index', models.IntegerField()),
                ('akun', models.CharField(max_length=255)),
                ('akun_key', models.CharField(db_index=True, max_length=128)),
                ('anggaran', models.FloatField(blank=True, null=True)),
                ('realisasi', models.FloatField(blank=True, null=True)),
                ('persentase', models.FloatField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='djpk.apbdreport')),
            ],
            options={
                'ordering': ['report', 'line_index'],
                'indexes': [models.Index(fields=['akun_key'], name='djpk_apbdli_akun_ke_fea86d_idx')],
                'unique_together': {('report', 'line_index')},
            },
        ),
        migrations.AddIndex(
            model_name='apbdreport',
            index=models.Index(fields=['tahun', 'report_type', 'periode'], name='djpk_apbdre_tahun_b2c937_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='apbdreport',
            unique_together={('region', 'tahun', 'report_type', 'periode')},
        ),
    ]
