# Generated by Django 5.0.6 on 2026-07-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DukcapilFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64)),
                ('layer_id', models.IntegerField()),
                ('level', models.CharField(choices=[('province', 'Provinsi'), ('regency', 'Kabupaten/Kota'), ('district', 'Kecamatan'), ('village', 'Desa/Kelurahan')], max_length=16)),
                ('url', models.TextField()),
                ('http_status', models.IntegerField()),
                ('row_count', models.IntegerField(default=0)),
                ('response_sha256', models.CharField(max_length=64)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='DukcapilIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64, unique=True)),
                ('label_id', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=32)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_string', models.BooleanField(default=False)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'field'],
            },
        ),
        migrations.CreateModel(
            name='DukcapilRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('level', models.CharField(choices=[('province', 'Provinsi'), ('regency', 'Kabupaten/Kota'), ('district', 'Kecamatan'), ('village', 'Desa/Kelurahan')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('parent_code', models.CharField(blank=True, max_length=16)),
                ('no_prop', models.IntegerField(blank=True, null=True)),
                ('no_kab', models.IntegerField(blank=True, null=True)),
                ('no_kec', models.IntegerField(blank=True, null=True)),
                ('no_kel', models.IntegerField(blank=True, null=True)),
                ('nama_prop', models.CharField(blank=True, max_length=255)),
                ('nama_kab', models.CharField(blank=True, max_length=255)),
                ('nama_kec', models.CharField(blank=True, max_length=255)),
                ('attributes', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetch_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='dukcapil.dukcapilfetchlog')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dukcapil.dukcapilregion')),
            ],
            options={
                'ordering': ['level', 'code'],
                'indexes': [models.Index(fields=['level'], name='dukcapil_du_level_715de6_idx'), models.Index(fields=['level', 'parent_code'], name='dukcapil_du_level_05fec3_idx'), models.Index(fields=['parent_code'], name='dukcapil_du_parent__28057e_idx')],
                'unique_together': {('level', 'code')},
            },
        ),
    ]
