# Generated by Django 5.0.6 on 2026-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukcapilregion',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='dukcapilregion',
            name='parent_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
