# Generated by Django 5.0.6 on 2026-07-10 07:16

from django.db import migrations, models


def backfill_period(apps, schema_editor):
    """Existing rows predate the period field — stamp them with the calendar
    month they were fetched, so they become the first snapshot in the series
    (and the unique (level, code, period) constraint holds)."""
    Region = apps.get_model("dukcapil", "DukcapilRegion")
    Log = apps.get_model("dukcapil", "DukcapilFetchLog")
    for model in (Region, Log):
        for row in model.objects.filter(period="").only("id", "fetched_at").iterator():
            model.objects.filter(id=row.id).update(period=row.fetched_at.strftime("%Y-%m"))


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0002_alter_dukcapilregion_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dukcapilregion',
            name='dukcapil_du_level_715de6_idx',
        ),
        migrations.RemoveIndex(
            model_name='dukcapilregion',
            name='dukcapil_du_level_05fec3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dukcapilregion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dukcapilfetchlog',
            name='period',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='dukcapilregion',
            name='period',
            field=models.CharField(db_index=True, default='', max_length=7),
        ),
        migrations.RunPython(backfill_period, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='dukcapilregion',
            unique_together={('level', 'code', 'period')},
        ),
        migrations.AddIndex(
            model_name='dukcapilregion',
            index=models.Index(fields=['level', 'period'], name='dukcapil_du_level_f8d8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='dukcapilregion',
            index=models.Index(fields=['level', 'period', 'parent_code'], name='dukcapil_du_level_99a853_idx'),
        ),
    ]
