# Generated by Django 5.0.6 on 2026-07-10 07:22

from django.db import migrations, models


def backfill_ancestor_codes(apps, schema_editor):
    """Populate prov/kab/kec codes for rows ingested before these fields
    existed, composing them from no_prop/no_kab/no_kec (prov=2, kab=4,
    kec=6 digits)."""
    Region = apps.get_model("dukcapil", "DukcapilRegion")
    for r in Region.objects.only("id", "no_prop", "no_kab", "no_kec").iterator():
        prov = f"{r.no_prop:02d}" if r.no_prop is not None else ""
        kab = f"{prov}{r.no_kab:02d}" if prov and r.no_kab is not None else ""
        kec = f"{kab}{r.no_kec:02d}" if kab and r.no_kec is not None else ""
        Region.objects.filter(id=r.id).update(prov_code=prov, kab_code=kab, kec_code=kec)


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0003_remove_dukcapilregion_dukcapil_du_level_715de6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dukcapilregion',
            name='dukcapil_du_parent__28057e_idx',
        ),
        migrations.AddField(
            model_name='dukcapilregion',
            name='kab_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='dukcapilregion',
            name='kec_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='dukcapilregion',
            name='prov_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.RunPython(backfill_ancestor_codes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='dukcapilregion',
            index=models.Index(fields=['level', 'period', 'prov_code'], name='dukcapil_du_level_26a37f_idx'),
        ),
        migrations.AddIndex(
            model_name='dukcapilregion',
            index=models.Index(fields=['level', 'period', 'kab_code'], name='dukcapil_du_level_7ba043_idx'),
        ),
        migrations.AddIndex(
            model_name='dukcapilregion',
            index=models.Index(fields=['level', 'period', 'kec_code'], name='dukcapil_du_level_a9ec1c_idx'),
        ),
    ]
