# Generated by Django 5.0.6 on 2026-07-10 11:39

from django.db import migrations, models


def backfill_name_status(apps, schema_editor):
    """Existing rows store the raw UPPERCASE name; re-derive the clean
    title-cased name + structured status from it."""
    from dukcapil.normalize import name_and_status

    Region = apps.get_model("dukcapil", "DukcapilRegion")
    batch = []
    for r in Region.objects.only("id", "level", "name").iterator():
        name, status = name_and_status(r.level, r.name)
        r.name, r.status = name, status
        batch.append(r)
        if len(batch) >= 2000:
            Region.objects.bulk_update(batch, ["name", "status"])
            batch = []
    if batch:
        Region.objects.bulk_update(batch, ["name", "status"])


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0004_remove_dukcapilregion_dukcapil_du_parent__28057e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukcapilregion',
            name='status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.RunPython(backfill_name_status, migrations.RunPython.noop),
    ]
