# Generated by Django 5.0.6 on 2026-07-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukcapil', '0006_village_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukcapilregion',
            name='luas_big',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
