# Generated by Django 5.0.6 on 2026-10-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetaIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label_id', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=32)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('dataset', models.CharField(max_length=64)),
                ('method', models.TextField()),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PetaLoadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('export_sha256', models.CharField(max_length=64)),
                ('areas', models.IntegerField()),
                ('values', models.IntegerField()),
                ('datasets', models.JSONField(default=dict)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PetaSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('url', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('bytes', models.BigIntegerField()),
                ('downloaded_at', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PetaValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PetaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('level', models.CharField(choices=[('province', 'Provinsi'), ('regency', 'Kabupaten/Kota'), ('district', 'Kecamatan')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('prov_code', models.CharField(db_index=True, max_length=2)),
                ('parent_code', models.CharField(blank=True, db_index=True, max_length=8)),
                ('area_km2', models.FloatField(null=True)),
                ('terrain_class', models.CharField(blank=True, max_length=32)),
                ('terrain_class_label', models.CharField(blank=True, max_length=64)),
                ('terrain_class_reason', models.TextField(blank=True)),
                ('highest_point', models.JSONField(null=True)),
                ('landcover_year', models.IntegerField(null=True)),
                ('terrain_provenance', models.JSONField(null=True)),
                ('landcover_provenance', models.JSONField(null=True)),
                ('load_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='peta.petaloadlog')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='petasourcefile',
            constraint=models.UniqueConstraint(fields=('dataset', 'key'), name='peta_sourcefile_unique'),
        ),
        migrations.AddField(
            model_name='petaregion',
            name='source_files',
            field=models.ManyToManyField(related_name='regions', to='peta.petasourcefile'),
        ),
        migrations.AddField(
            model_name='petavalue',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='peta.petaindicator'),
        ),
        migrations.AddField(
            model_name='petavalue',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='peta.petaregion'),
        ),
        migrations.AddIndex(
            model_name='petavalue',
            index=models.Index(fields=['indicator', 'value'], name='peta_petava_indicat_5ec1b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='petavalue',
            constraint=models.UniqueConstraint(fields=('region', 'indicator'), name='peta_value_unique'),
        ),
    ]
