# Generated by Django 5.0.6 on 2026-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='petavalue',
            name='peta_value_unique',
        ),
        migrations.RemoveIndex(
            model_name='petavalue',
            name='peta_petava_indicat_5ec1b8_idx',
        ),
        migrations.AddField(
            model_name='petaindicator',
            name='yearly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petaregion',
            name='nightlights_provenance',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='petavalue',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='petavalue',
            index=models.Index(fields=['indicator', 'year', 'value'], name='peta_petava_indicat_d7a620_idx'),
        ),
        migrations.AddConstraint(
            model_name='petavalue',
            constraint=models.UniqueConstraint(fields=('region', 'indicator', 'year'), name='peta_value_unique_year'),
        ),
    ]
