# Generated by Django 5.0.6 on 2026-07-05 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_simdasitable_options_alter_variable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(max_length=16)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('turvar_id', models.CharField(default='0', max_length=16)),
                ('turvar_label', models.CharField(blank=True, max_length=255)),
                ('value', models.FloatField()),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='catalog.domain')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='catalog.perioddata')),
                ('source_check_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.coveragechecklog')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='catalog.variable')),
            ],
            options={
                'ordering': ['variable_id', 'domain_id', 'period_id', 'turvar_id'],
                'indexes': [models.Index(fields=['domain', 'period'], name='stats_datap_domain__a6dc37_idx'), models.Index(fields=['variable', 'period'], name='stats_datap_variabl_c61a2a_idx'), models.Index(fields=['admin_level', 'year'], name='stats_datap_admin_l_1af491_idx')],
                'unique_together': {('variable', 'domain', 'period', 'turvar_id')},
            },
        ),
    ]
