# Generated by Django 5.0.6 on 2026-07-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_subject_metadata_crawled_at'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['variable_id', 'domain_id', 'period_id', 'vervar_id', 'turvar_id']},
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='vervar_id',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='vervar_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together={('variable', 'domain', 'period', 'vervar_id', 'turvar_id')},
        ),
    ]
