# Generated by Django 5.0.6 on 2026-07-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_datapoint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='turvar_label',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='vervar_label',
            field=models.TextField(blank=True),
        ),
    ]
