# Generated by Django 5.0.6 on 2026-07-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_subject_metadata_crawled_at'),
        ('stats', '0003_alter_datapoint_turvar_label_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['admin_level', 'variable'], name='stats_datap_admin_l_a96a24_idx'),
        ),
    ]
