# Generated by Django 5.0.6 on 2026-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_variable_stat_admin_levels_variable_stat_data_points_and_more'),
        ('stats', '0004_datapoint_stats_datap_admin_l_a96a24_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datapoint',
            index=models.Index(fields=['variable', 'admin_level', 'year'], name='stats_datap_variabl_64cd09_idx'),
        ),
    ]
