# Generated by Django 5.0.6 on 2026-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_datapoint_stats_datap_variabl_64cd09_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_level', models.CharField(max_length=16, unique=True)),
                ('data_points', models.PositiveBigIntegerField(default=0)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
